### ISSUE TITLE
DB maintenance

### ISSUE THREAD

**Issue by pbiggar** [darklang/classic-dark#15]
## Announcing intentions
- [x] announce intentions in #status
- [x] tweet
- [x] mastodon
- [x] post in #general
- [x] 3 hr downtime

## Prep
- [x] have devcontainer built on latest stable-dark

## Once it starts
- [x] post to #status again righ
- [x] reply to intentions tweet
- [x] reply to intentions toot
- [x] post in #general
- [x] update status.darklang.com (via betterstatus)
- [x] turn off pagerduty or phones
- [x] turn off bwdserver (via k8s)
  - [x] kubectl scale --replicas=0 -n darklang deployment/bwdserver-deployment 
- [x] leave apiserver up (though, requests will largely fail upon DB connection)
- [x] turn off cronchecker (turn crons down to 0 in kubernetes, restart)
  - [x] kubectl scale --replicas=0 -n default deployment/cronchecker-deployment 
- [x] turn off queueworker
  - [x] kubectl scale --replicas=0 -n darklang deployment/queueworker-deployment

## Operations
- [x] sit with Google while they shrink the DB from 10TB (2 steps, 2:30hr)
- [x] reduce availability and CPU (16 -> 12)
- [x] don't upgrade DB version
- [x] throughout, record activity in #operations

## Turning things back on
- [x] update some [LaunchDarkly](https://app.launchdarkly.com/default/production/features/queue-max-concurrent-events-per-worker/targeting) settings to 16
- [x] reenable pagerduty
- [x] turn up bwdserver to 2
  - [x] kubectl scale --replicas=2 -n darklang deployment/bwdserver-deployment
- [x] check apiserver
- [x] change cronchecker to 1
  - [x] kubectl scale --replicas=1 -n default deployment/cronchecker-deployment
- [x] turn on queueworker
  - [x] kubectl scale --replicas=2 -n darklang deployment/queueworker-deployment

## Announce done
- [x] announce in #status
- [x] announce done in #general
- [x] mastodon
- [x] tweet done

**Comment by StachuDotNet** [comment]
- [ ] turn back on deployment/exechost-deployment
- [ ] turn back on deployment/editor-deployment
- [ ] turn back on deployment/garbage-collector-deployment

**Comment by StachuDotNet** [comment]
Note: google didn't end up performing a second shrink - they stopped communicating after the first shrink, so we decided to wrap things up without the second one.
